---
- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'CentOS'
  tags: 
    - repo

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'CentOS'
  tags: 
    - repo

- name: Add the EPEL repo to centos
  yum: name=epel-release
  when: "ansible_distribution == 'CentOS'"
  tags: 
    - repo